/**
 * CPI-U inflation helpers for the Brooklyn page.
 *
 * `public/data/cpi-us.json` (generated by `scripts/etl/reference/cpi.ts`) holds
 * the monthly US CPI-U index. We use it two ways on the line chart:
 *   - "real" view: deflate each nominal $/sqft point to constant (latest) dollars
 *     so the line shows purchasing-power change, not inflation.
 *   - "indexed" view (CPI-independent): rebase each series to 100 at its start so
 *     trajectories are comparable regardless of price level.
 */
import type { DataPoint } from '@/types';

export interface CpiData {
  source: string;
  latest: DataPoint;
  /** Monthly index points, ascending by date. */
  series: DataPoint[];
}

/**
 * Build a deflator that converts a nominal value at `date` into constant
 * latest-dollar terms: `value * latestCpi / cpi(date)`. CPI is monthly, so we
 * pick the latest index point at or before `date` (clamped to the series ends).
 */
export function makeDeflator(cpi: CpiData): (point: DataPoint) => DataPoint {
  // Defensive: ignore any non-positive index points so a delayed/missing month
  // can never divide-by-zero (the ETL already filters these out).
  const series = cpi.series.filter((p) => p.value > 0);
  const latest = cpi.latest.value > 0 ? cpi.latest : series[series.length - 1];
  const cpiAt = (date: number): number => {
    let chosen = series[0].value;
    for (const p of series) {
      if (p.date > date) break;
      chosen = p.value;
    }
    return chosen;
  };
  return (point) => {
    const cpiNow = cpiAt(point.date);
    if (!cpiNow) return { ...point };
    return {
      ...point,
      value: Number(((point.value * latest.value) / cpiNow).toFixed(2)),
    };
  };
}

/** Rebase a series to 100 at its first non-zero point (skips leading zeros). */
export function indexToBase(points: DataPoint[]): DataPoint[] {
  const base = points.find((p) => p.value > 0)?.value;
  if (!base) return points;
  return points.map((p) => ({
    ...p,
    value: p.value > 0 ? Number(((p.value / base) * 100).toFixed(1)) : 0,
  }));
}
