locals {
  # Define the Airflow environment name
  airflow_environment_name = "Vislet-Airflow"

  # Default team tag
  team_tag = "vislet"

  # List of bucket names to be used as DAG outputs
  s3_bucket_names = {
    prod = []
  }

  # Bucket where airflow DAGS, plugins, and
  # requirements.txt are loaded from
  airflow_dags_s3_bucket_name = {
    prod = "vislet-airflow-data-prod"
  }

  # Default AWS VPC name to use for airflow
  airflow_vpc_name = {
    prod = "vislet-vpc"
  }

  # Default AWS subnet IDs to use for airflow
  airflow_subnet_id_list = {
    prod = [
      "subnet-06aba32c0ca2807ee",
      "subnet-0b261865a15c0529b"
    ]
  }

  # Override default service tag for data buckets and SQS queues when enabled
  data_service_tag = "vislet-data"

  # SSM root path for reading parameter store secrets
  # arn:aws:ssm:${region}:${account_id}:parameter/${ssm_parameter_path}/*
  ssm_parameter_path = "vislet-airflow"

  # Enable SQS queues for all Airflow DAG output buckets
  sqs = {
    create = false
  }

  # Enable Kinesis subscriptions to Cloudwatch logs
  # for logs generated by Apache Airflow
  logstream = {
    create = false
  }
}
