name: Lint
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
          check-latest: true
      - run: npm install
      - run: npm run lint
      - run: npm run prettier:check
      - run: npm run typecheck
      - run: npm audit --audit-level=high
