name: CI for MWAA
on:
  push:
    branches:
	  - main

jobs:
	deploy:
	  runs-on: ubuntu-latest
	  steps:
	  - uses: actions/checkout@main
	  - uses: /s3-sync-action@master
	    with:
	      args: --acl private --follow-symlinks --delete --exclude '.git/*'
	    env:
	      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
	      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
	      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
	      AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
